name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.4.5'
            otp: '19.3.6.13'
          - elixir: '1.11.2'
            otp: '23.0.3'
            check_formatted: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.5.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Check code format
        run: mix format --check-formatted
        if: matrix.check_formatted

      - name: Install Dependencies
        run: mix deps.get

      - name: Check for compile warnings
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
